### ISSUE TITLE
FR: Ability to get other values from the formset

### ISSUE THREAD

**Issue by gmcz** [serieseight/statamic-automagic#1]
I have several other key/value pairs in my formsets beyond the standard, for example:

```yaml
title: An Awesome Form
fields:
  cool_thing:
    display: 'What is a Cool Thing?'
    detail: 'Please tell us what a Cool Thing is so we can know your answer.'
    type: textarea
```
I would really like to be able to include this in the automagic email templates as well! If I'm happy to work on this and submit a PR but I'd need a bit of direction to get going.
